version: '3.7'
services:
  asc-service:
    build:
      context: toys-api-service
      dockerfile: Dockerfile
    networks:
      private:
        # the aliases are not required, but are useful if the applications want to internally
        # reference each other by host name
        aliases:
        - "asc-service"
      public:
    ports:    
      - "9813:3002"   

  asc-nginx:
    build:
      context: asc-server
      dockerfile: Dockerfile
    depends_on:
      - "asc-service"   
    networks:
      private:
        # the aliases are not required, but are useful if the applications want to internally
        # reference each other by host name
        aliases:
        - "asc-nginx"
      public:
    ports:    
      - "9812:80"  
    volumes:
      - /home/core/shared/prod/asc-server/html:/usr/local/openresty/nginx/html
      - /home/core/shared/prod/asc-server/templates:/usr/local/openresty/nginx/templates
      - /home/core/shared/prod/asc-server/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf 
      - /home/core/shared/prod/asc-server/conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      # this differs from a normal -v folder mount to maintaine with/out traefik 

networks:
  # everything that is *only* on "internal network" cannot talk to WAN
  private:
    internal: true
  # add this network to a container to make it talk to the rest of the world
  public: